- name: varibales to print
  hosts: web
  vars: # Play level variable, all tasks in this play have access to this vars.
    COURSE: "Devops with AWS"
    TEACHER: "Siva"
    DURATION: "1 HR"
  tasks:
  - name: print the variables
    ansible.builtin.debug:
      msg: "Hi, Learning Devops from {{COURSE}} course, taught by {{TEACHER}} and time is {{DURATION}}"

  - name: print the variables again
    vars: #Task level varibales; Ansible gets printed
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Hi, Learning Devops from {{COURSE}} course, taught by {{TEACHER}} and time is {{DURATION}}"

  - name: print the variables again and again
    ansible.builtin.debug:
      msg: "Hi, Learning Devops from {{COURSE}} course, taught by {{TEACHER}} and time is {{DURATION}}"