#Taking variables from other files
- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
    - name: print the course info
      ansible.builtin.debug:
        msg: "Hi, Learning Devops from {{COURSE}} course, taught by {{TEACHER}} and time is {{DURATION}}"