# Taking variables from user input
# Prompt means - confidential information
- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE                           # Name of the variable
    prompt: Please enter the course name
    private: false
  - name: TEACHER                          # Name of the variable
    prompt: Please enter the teacher name
    private: false
  - name: DURATION                         # Name of the variable
    prompt: Enter the duration of course
    private: false                        # Not Confidential, not kept secret and can see what's getting typed.

  tasks:
  - name: Print the course info
    ansible.builtin.debug:
      msg: "Hi, Learning Devops from {{COURSE}} course, taught by {{TEACHER}} and time is {{DURATION}}"
