- name: demo on filters
  hosts: local
  connection: local
  tasks:
  - name: print the default varible
    ansible.builtin.debug:
      msg: "Hello {{ course | default('Ansible') }}" 
  
  - name: convert to uppercase for any name given
    vars:
      greeting: "Hello John"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"
